# ClusterRoleBinding
{{- if or .Values.rbac.clusterAdminRole .Values.rbac.clusterReadOnlyRole }}
# Cluster role binding for clusterAdminRole == true or clusterReadOnlyRole=true
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "k8s-for-mikrotik-loadbalancer.name" . }}
    chart: {{ template "k8s-for-mikrotik-loadbalancer.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "k8s-for-mikrotik-loadbalancer.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
#   {{ if .Values.rbac.clusterAdminRole -}}
# cluster-admin
# {{- else if .Values.rbac.clusterReadOnlyRole -}}
# {{ template "k8s-for-mikrotik-loadbalancer.fullname" . }}-readonly
# {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8s-for-mikrotik-loadbalancer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
